// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlhznSherNvH9Y_ceMXj2I2QPtxj5f4a4',
    appId: '1:490911604718:web:25aa08559ed5fa1d8478ff',
    messagingSenderId: '490911604718',
    projectId: 'gachitore-4d74d',
    authDomain: 'gachitore-4d74d.firebaseapp.com',
    storageBucket: 'gachitore-4d74d.firebasestorage.app',
    measurementId: 'G-H856EJ40B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxGtv9PDYpgRATQ9VcYUO-M5WCU0bRiZQ',
    appId: '1:490911604718:android:b494c64ac425ca608478ff',
    messagingSenderId: '490911604718',
    projectId: 'gachitore-4d74d',
    storageBucket: 'gachitore-4d74d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDLHv73XgN_5i0dcVuSESp_SeViCKvsy0',
    appId: '1:490911604718:ios:32cf77cbec29b84b8478ff',
    messagingSenderId: '490911604718',
    projectId: 'gachitore-4d74d',
    storageBucket: 'gachitore-4d74d.firebasestorage.app',
    iosBundleId: 'com.gachtore.gachitore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDLHv73XgN_5i0dcVuSESp_SeViCKvsy0',
    appId: '1:490911604718:ios:32cf77cbec29b84b8478ff',
    messagingSenderId: '490911604718',
    projectId: 'gachitore-4d74d',
    storageBucket: 'gachitore-4d74d.firebasestorage.app',
    iosBundleId: 'com.gachtore.gachitore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlhznSherNvH9Y_ceMXj2I2QPtxj5f4a4',
    appId: '1:490911604718:web:3df10462670c80da8478ff',
    messagingSenderId: '490911604718',
    projectId: 'gachitore-4d74d',
    authDomain: 'gachitore-4d74d.firebaseapp.com',
    storageBucket: 'gachitore-4d74d.firebasestorage.app',
    measurementId: 'G-P06KRL1EN1',
  );
}
